-- Create database and schemas
CREATE DATABASE IF NOT EXISTS SMART_FACTORY_DWH;
USE DATABASE SMART_FACTORY_DWH;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS FACTORY_ETL_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

-- Create roles
CREATE ROLE IF NOT EXISTS FACTORY_ETL_ROLE;
CREATE ROLE IF NOT EXISTS FACTORY_ANALYST_ROLE;

-- Grant privileges
GRANT USAGE ON WAREHOUSE FACTORY_ETL_WH TO ROLE FACTORY_ETL_ROLE;
GRANT USAGE ON WAREHOUSE FACTORY_ETL_WH TO ROLE FACTORY_ANALYST_ROLE;

GRANT USAGE ON DATABASE SMART_FACTORY_DWH TO ROLE FACTORY_ETL_ROLE;
GRANT USAGE ON DATABASE SMART_FACTORY_DWH TO ROLE FACTORY_ANALYST_ROLE;

GRANT USAGE ON SCHEMA SMART_FACTORY_DWH.ANALYTICS TO ROLE FACTORY_ETL_ROLE;
GRANT USAGE ON SCHEMA SMART_FACTORY_DWH.STAGING TO ROLE FACTORY_ETL_ROLE;
GRANT USAGE ON SCHEMA SMART_FACTORY_DWH.ANALYTICS TO ROLE FACTORY_ANALYST_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SMART_FACTORY_DWH.ANALYTICS TO ROLE FACTORY_ETL_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SMART_FACTORY_DWH.STAGING TO ROLE FACTORY_ETL_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA SMART_FACTORY_DWH.ANALYTICS TO ROLE FACTORY_ANALYST_ROLE;
