USE DATABASE SMART_FACTORY_DWH;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DEVICE (
    DEVICE_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEVICE_ID VARCHAR(50) NOT NULL,
    DEVICE_NAME VARCHAR(100),
    DEVICE_TYPE VARCHAR(50),
    LOCATION VARCHAR(100),
    INSTALL_DATE DATE,
    STATUS VARCHAR(20),
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    EFFECTIVE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    EXPIRY_DATE TIMESTAMP DEFAULT '9999-12-31'::TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Note: We use an IDENTITY/AUTOINCREMENT column for the surrogate key (DEVICE_KEY).
-- The DEVICE_ID is the natural key from the source system.
