USE DATABASE SMART_FACTORY_DWH;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_SENSOR_DATA (
    SENSOR_DATA_KEY BIGINT AUTOINCREMENT PRIMARY KEY,
    DEVICE_KEY INT REFERENCES ANALYTICS.DIM_DEVICE(DEVICE_KEY),
    DATE_KEY INT REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    READING_TIMESTAMP TIMESTAMP NOT NULL,
    TEMPERATURE DECIMAL(8,3),
    HUMIDITY DECIMAL(8,3),
    PRESSURE DECIMAL(8,3),
    VIBRATION DECIMAL(8,4),
    VOLTAGE DECIMAL(8,3),
    CURRENT_AMPS DECIMAL(8,3),
    HOUR_OF_DAY INT,
    IS_ANOMALY BOOLEAN DEFAULT FALSE,
    ETL_BATCH_ID VARCHAR(50),
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) CLUSTER BY (DATE_KEY, DEVICE_KEY);
