USE DATABASE SMART_FACTORY_DWH;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_ALERTS (
    ALERT_KEY BIGINT AUTOINCREMENT PRIMARY KEY,
    DEVICE_KEY INT REFERENCES ANALYTICS.DIM_DEVICE(DEVICE_KEY),
    DATE_KEY INT REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    ALERT_TIMESTAMP TIMESTAMP NOT NULL,
    ALERT_TYPE VARCHAR(50),
    SEVERITY VARCHAR(20),
    METRIC VARCHAR(50),
    THRESHOLD_VALUE DECIMAL(10,3),
    ACTUAL_VALUE DECIMAL(10,3),
    MESSAGE TEXT,
    IS_ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
    ETL_BATCH_ID VARCHAR(50),
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
