-- Example queries that Airflow would execute or use as views

USE DATABASE SMART_FACTORY_DWH;

-- 1. Create Staging Tables for Incremental Load
CREATE OR REPLACE TABLE STAGING.SENSOR_DATA_STG (
    ID BIGINT,
    DEVICE_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP,
    TEMPERATURE DECIMAL(8,3),
    HUMIDITY DECIMAL(8,3),
    PRESSURE DECIMAL(8,3),
    VIBRATION DECIMAL(8,4),
    VOLTAGE DECIMAL(8,3),
    CURRENT_AMPS DECIMAL(8,3)
);

CREATE OR REPLACE TABLE STAGING.DEVICE_MASTER_STG (
    DEVICE_ID VARCHAR(50),
    DEVICE_NAME VARCHAR(100),
    DEVICE_TYPE VARCHAR(50),
    LOCATION VARCHAR(100),
    INSTALL_DATE DATE,
    STATUS VARCHAR(20),
    UPDATED_AT TIMESTAMP
);

-- 2. MERGE statement for DIM_DEVICE (SCD Type 2 logic simplified)
-- In a real scenario, this involves closing old records and inserting new ones.
-- This simple merge acts mostly as an upsert for demonstration.
MERGE INTO ANALYTICS.DIM_DEVICE T
USING STAGING.DEVICE_MASTER_STG S
ON T.DEVICE_ID = S.DEVICE_ID AND T.IS_CURRENT = TRUE
WHEN MATCHED AND (T.STATUS != S.STATUS OR T.LOCATION != S.LOCATION) THEN
    UPDATE SET 
        T.IS_CURRENT = FALSE, 
        T.EXPIRY_DATE = CURRENT_TIMESTAMP(),
        T.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (DEVICE_ID, DEVICE_NAME, DEVICE_TYPE, LOCATION, INSTALL_DATE, STATUS, EFFECTIVE_DATE)
    VALUES (S.DEVICE_ID, S.DEVICE_NAME, S.DEVICE_TYPE, S.LOCATION, S.INSTALL_DATE, S.STATUS, CURRENT_TIMESTAMP());
    
-- Note: A second statement would be needed to INSERT the new versions for the updated rows to complete SCD Type 2.

-- 3. Load FACT_SENSOR_DATA looking up DEVICE_KEY and DATE_KEY
INSERT INTO ANALYTICS.FACT_SENSOR_DATA (
    DEVICE_KEY, DATE_KEY, READING_TIMESTAMP, TEMPERATURE, HUMIDITY, 
    PRESSURE, VIBRATION, VOLTAGE, CURRENT_AMPS, HOUR_OF_DAY, ETL_BATCH_ID
)
SELECT 
    D.DEVICE_KEY,
    CAST(TO_CHAR(S.TIMESTAMP, 'YYYYMMDD') AS INT) AS DATE_KEY,
    S.TIMESTAMP,
    S.TEMPERATURE,
    S.HUMIDITY,
    S.PRESSURE,
    S.VIBRATION,
    S.VOLTAGE,
    S.CURRENT_AMPS,
    EXTRACT(HOUR FROM S.TIMESTAMP),
    'BATCH_ID_PLACEHOLDER'
FROM STAGING.SENSOR_DATA_STG S
LEFT JOIN ANALYTICS.DIM_DEVICE D 
    ON S.DEVICE_ID = D.DEVICE_ID AND D.IS_CURRENT = TRUE;

-- 4. Analytical Views

-- Hourly Averages
CREATE OR REPLACE VIEW ANALYTICS.VW_HOURLY_DEVICE_STATS AS
SELECT 
    DATE_KEY,
    DEVICE_KEY,
    HOUR_OF_DAY,
    AVG(TEMPERATURE) AS AVG_TEMP,
    MAX(TEMPERATURE) AS MAX_TEMP,
    AVG(VIBRATION) AS AVG_VIBE,
    MAX(VIBRATION) AS MAX_VIBE
FROM ANALYTICS.FACT_SENSOR_DATA
GROUP BY DATE_KEY, DEVICE_KEY, HOUR_OF_DAY;

-- Alert Summary
CREATE OR REPLACE VIEW ANALYTICS.VW_ALERT_SUMMARY AS
SELECT
    DATE_KEY,
    DEVICE_KEY,
    SEVERITY,
    COUNT(*) AS ALERT_COUNT
FROM ANALYTICS.FACT_ALERTS
GROUP BY DATE_KEY, DEVICE_KEY, SEVERITY;
